name: GIPHY Generator

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [opened, edited]
    
jobs:
  giphy-generator:
    name: GIPHY Generato
    runs-on: ubuntu-latest
  
    steps:
      - name: GIPHY Generator
        id: giphy_generator
        uses: IAmHughes/giphy-generator@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }} 
        with:
          rating: 'g'
          lang: 'en'
